### ISSUE TITLE
getCsrfInput() has been deprecated

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/sprout-docs#16]
The Sprout Forms docs use `getCsrfInput()` on the [Craft 3 version of the form code](https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#upgrading-to-craft-3). This should be updated to `csrfInput()`.

**Comment by BenParizek** [comment]
Thanks @darylknight 

We'll get these updated in the next push.
